### ISSUE TITLE
smartapi registry loads first 100 entries at the load time

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#105]
Currently the pagination ends at page 5, while we have over 200 records:

![image](https://user-images.githubusercontent.com/130158/108277360-277efc80-712e-11eb-8bc6-48acba301ea3.png)

Time to switch to server-side pagination?

**Comment by marcodarko** [comment]
Pagination is handled on the server now, all pagination is now based on query total and left to ES to handle.
