### ISSUE TITLE
Source status shows differently with "My API" badge and "Source status" badge

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#111]
This is not specific for one API entry, but here is an example:

https://smart-api.info/registry?q=smartapi

![image](https://user-images.githubusercontent.com/130158/109720605-2b177800-7b5f-11eb-851b-562f91bcf22f.png)

**Comment by marcodarko** [comment]
Issue was because there was good statuses that include (200 and 299) I was only taking into consideration 200. All statuses should be correct now.
