### ISSUE TITLE
type selection bug in metakg UI

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#116]
The UI at https://smart-api.info/portal/translator/metakg provides boxes for "Input type", "relationship" and "output type".  If I make a selection for "output type" and then an "input type", I see the filtered set of APIs as expected.  But if I first select an "input type", the selector for the "output type" does not work for me.  The autocomplete drop-down selector shows up fine, but selecting an option does not apply the filter (nor does the button show up below the selector).

**Comment by marcodarko** [comment]
Typo causing the issue has been fixed, it was from copying and pasting and forgetting to change a variable name.
