### ISSUE TITLE
support v2 swagger API metadata registration

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#12]
We should allow v2 swagger/openapi metadata to register, so that the API documentation and API metadata editor will still work, but SmartAPI extensions won't be supported for v2 metadata.

TODO:
- [x] smartapi backend API should validate standard v2 metadata
- [x] for the API save functionality, only some basic API info (e.g. under 'info' field) will be extracted and made searchable. The raw v2 metadata will be saved as it is (in "~raw" field)
- [x] "Add an API" page should validate v2 metadata, and provide a warning msg for v2
- [x] API registry page should display OAS2 and OAS3 labels

**Comment by briandoconnor** [comment]
+1 on this

**Comment by newgene** [comment]
The json-schema file for validating v2 swagger metadata:

https://github.com/swagger-api/swagger-editor/blob/v3.2.9/src/plugins/validate-json-schema/structural-validation/swagger2-schema.js

**Comment by cmungall** [comment]
any progress on this?

**Comment by newgene** [comment]
We are close to wrapping it up now, targeting early next week.

**Comment by newgene** [comment]
OK, we have deployed a new version of SmartAPI app last week with the support of v2 OpenAPI metadata. Please give it a try. Note that there are no smartapi extension fields supported in v2, just the plain v2 OpenAPI.

ref: https://github.com/SmartAPI/smartAPI/issues/12

**Comment by marcodarko** [comment]
@cmungall @briandoconnor 
Our latest release now supports Swagger v2 metadata submissions! You can view your API documentation via the registry or on your user dashboard. 

Note - V2 apis will however experience limited functionality and we still recommend you update them to v3 specification so be fully included in SmartAPI and BioThings Explorer. 

Thank you for the great feedback and hope you enjoy using our app!
