### ISSUE TITLE
add some common quick filters for translator registry

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#121]
some translator-specific quick filters (or query examples), like a buttons or links under the search bar in /registry/translator page:

* all KPs
* all ARAs
* all BioThings APIs
* all TRAPIs
* TRAPIs v1.0
* TRAPIs v1.1

**Comment by marcodarko** [comment]
https://smart-api.info/registry/translator?tags=translator dynamic filters based on aggregations on translator tagged docs
