### ISSUE TITLE
Update SmartAPI API metadata

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#122]
SmartAPI API metadata is hosted here: https://github.com/SmartAPI/smartapi_registry/blob/master/SmartAPI/smartapi_openapi.yml.

Let's update it to match the current implementation.

related: #92

**Comment by marcodarko** [comment]
@colleenXu you already did this right?

**Comment by colleenXu** [comment]
I haven't updated the smartapi yaml for the smartapi registry (which is what that looks like...). Maybe @newgene did it?

**Comment by NikkiBytes** [comment]
We updated [this](https://github.com/SmartAPI/smartapi_registry/blob/master/SmartAPI/smartapi_openapi.yml) recently with the metakg, is there anything more to update or should we close this? @newgene

**Comment by NikkiBytes** [comment]
Updated with `/metakg` and `/metakg/paths` documentation, closing as complete.
