### ISSUE TITLE
Evaluate OMIM for inclusion in registry 

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#129]
OMIM is a valuable resource for mendelian diseases and their links to human genes.  OMIM provides an API, described at https://www.omim.org/api, which requires registration and use of an API key.  **_When/if_** the Translator Architecture Committee figures out a mechanism to support the use of API keys (proposal here: https://github.com/NCATSTranslator/TranslatorArchitecture/discussions/42#discussioncomment-755133), then the OMIM API would be a useful one to include in the SmartAPI registry for inclusion in BTE queries.  Until then, consider this issue to be on hold.

**Comment by NikkiBytes** [comment]
@andrewsu is this still relevant? If not, please feel free to close.
