### ISSUE TITLE
Add smartapi custom branding to swagger_ui installation

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#13]
Some instruction here:
https://swagger.io/docs/swagger-tools/#customization-36

Can we hide the default header bar?

**Comment by newgene** [comment]
Can install swagger-ui locally by pulling this repo: https://github.com/swagger-api/swagger-ui, and then browse dist/index.html file.

**Comment by newgene** [comment]
Ideally, it would be nice if we can hide those empty-tags, like rendered in [this one](http://smart-api.info/ui/?url=/api/metadata/14cfbb82d72211adde316005a84d6e66).

**Comment by marcodarko** [comment]
Managed to hide the default bar, still looking into hiding the empty tags..

**Comment by marcodarko** [comment]
UI has been embedded and customized*
