### ISSUE TITLE
CORS error accessing ICEES meta_knowledge_graph endpoint through smartAPI

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#131]
When trying to execute this query https://smart-api.info/ui/9dd890397a7b8d98fbe247d56cac2b8f#/trapi/predicates_meta_knowledge_graph_get through the SmartAPI interface, I get this error

> Failed to fetch.
Possible Reasons:
CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.

![image](https://user-images.githubusercontent.com/2635409/127524811-1a2e5889-26e0-483a-9172-68293ecf0e55.png)

Directly accessing that endpoint https://icees.renci.org:16341/meta_knowledge_graph gives the expected results

I have not tested whether this is specific to this API/endpoint or whether it is a generic issue

**Comment by marcodarko** [comment]
Issue has been resolved by provider, no action had to be taken from our side.
