### ISSUE TITLE
slugs not working

### ISSUE THREAD

**Issue by CaseyTa** [SmartAPI/smartAPI#144]
We used to have a working slug `cohd.smart-api.info` which is no longer working. Instead of showing the COHD API, it's showing the main SmartAPI home page. Tried deleting and re-creating the slug, but it's still not working. 

Also tested `mygene.smart-api.info`, but that's also not working.

**Comment by marcodarko** [comment]
Hi @CaseyTa thanks for bringing this to my attention there was a small bug in a recent change, it's been fixed, feel free to try it!

**Comment by CaseyTa** [comment]
Working for me now. Thanks so much for the quick fix, @marcodarko!
