### ISSUE TITLE
Successful registration event redirect

### ISSUE THREAD

**Issue by david4096** [SmartAPI/smartAPI#15]
When completing a registration event, I would like to navigate to the created API to show the results of the registration. Currently, the browser flashes a success message and leaves the client at the main page.

**Comment by marcodarko** [comment]
@david4096 Hi David,
We kept this in mind for our newest deploy and now you will be prompted with a link immediately after a successful submission to your API documentation. Quick links to your API docs are also available via the user dashboard.  Thanks again for the great feedback!
