### ISSUE TITLE
Transfer SRI Reference Graph API entry from Kent Shefchek to Tim Putman

### ISSUE THREAD

**Issue by putmantime** [SmartAPI/smartAPI#159]
## Transfer of Ownership

Fill this out if you would like to transfer ownership of an API entry to someone else or claim ownership of one.

**Note: This transfer of ownership requests can only come from a registered user and go to another registered user on SmartAPI**.

  

*Let's start! First, tell us who you are*

* **I'm am Tim Putman @putmantime**

- [ ] the person transferring ownership of my API

- [x] the person that this API is being transferred to

- [ ] a third party requesting a special transfer (please provide details)

  

* What is the ***name*** and ***id*** of the API you would like to transfer? *eg. MyAPI : 124094327094378*

  
 SRI Reference KG: 1a41e3cd15f2b3bfa21c99900bfa1720

* What is the ***name*** and ***username*** of the person that this API currently belongs to? *eg. Jane Doe @janedoe1

  Kent Shefchek @kshefchek
  

* What is the ***name*** and ***username*** of the person that this API is being transferred to? *eg. John Doe @johndoe1*
Tim Putman @putmantime
  
  

* What is the reason this transfer of ownership is being requested?

  Kent has left TISLab
  

Thank you! We will review this request ASAP and will inform you of the status of the transfer.

**Comment by marcodarko** [comment]
@putmantime The API registration is all yours. You should see this item in your dashboard now, thank you!
