### ISSUE TITLE
Validation passes but leads to UI error

### ISSUE THREAD

**Issue by david4096** [SmartAPI/smartAPI#16]
When adding a version of an API it passes validation but doesn't render properly once being added, possibly because of a lack of contact name. In the registry view, after the API metadata has been added, clicking for more details causes an unexpected JavaScript error looking for a `name` property.

To fix this, either add validation for the fields assumed by the downstream view, or guard for the error in the UI code.

**Comment by marcodarko** [comment]
@david4096 We have handled this error for no data in that field in the next update of the app coming soon! Thank you for bringing this up to our attention.

**Comment by marcodarko** [comment]
The issue has been resolved on our latest release, thank you again for bringing this up to our attention!
