### ISSUE TITLE
Create a github commit hook for auto refreshing API metadata

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#17]
This feature actually has been added by @cyrus0824 on 87f19581a5f3f1dcfc1db6beb84d0c3386494683 already. This issue will serve as a record for related instruction.

**Comment by cyrus0824** [comment]
![webhook](https://user-images.githubusercontent.com/5504514/39643076-6132a2c6-4f88-11e8-9433-c284f6a16a48.jpeg)

**Comment by cyrus0824** [comment]
One caveat with this is that there seems to be caching on retrieving the API metadata from raw.githubusercontent.com (I think 300 seconds - 5 minutes).  If you do multiple pushes within a 5 minute period, the pushes will each trigger a webhook push event, but on the reload of the API metadata from raw.githubusercontent, we would get a cached copy.

**Comment by cyrus0824** [comment]
Also worth pointing out that it *should* be able to handle multiple yml files in one repository (and multiple commits per push - up to 20).  Only the files touched in the commit will be refreshed.
