### ISSUE TITLE
Support metakg queries with biolink model's semantic descendants

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#185]
Each edge in SmartAPI's metakg contains `subject`, `object`, `predicate` fields which are the terms based on the biolink model. We should add the metakg query support for searching on either of these fields by optionally expanding to include all descendant terms.

We can use [biolink-model-toolkit](https://github.com/biolink/biolink-model-toolkit) to get the descendant of a given term.

In metakg's query handler, we can add explicit `subject`, `object` and `predicate` query parameters, and an optional `expand` parameter when can take values of `subject`, `object` and `predicate` (include their combinations), so that we can expand either or multiple fields when needed. Default is still not expanding these terms.

**Comment by newgene** [comment]
This is pending on the completion of #179

**Comment by NikkiBytes** [comment]
@newgene Is this related to the `&expand` option we added to the metakg and pathfinder?

**Comment by newgene** [comment]
@NikkiBytes yes, maybe you can add a brief usage comment of this `expand` parameter and then we can close this one.

**Comment by NikkiBytes** [comment]
Implemented feature in `/metakg` and and `/metakg/paths` endpoint, with `&expand=` option.
Currently it accepts 1 or more of the options: subject, object, predicate, node, edge, or all.  
i.e https://smart-api.info/api/metakg/?subject=BiologicalEntity&object=BiologicalEntity&expand=subject 

To view a summary of the terms that were found when expanded, use `&rawquery=1`:
https://smart-api.info/api/metakg/?subject=BiologicalEntity&object=BiologicalEntity&expand=subject&rawquery=1
