### ISSUE TITLE
transfer Multiomics Wellness API rtroper->gglusman

### ISSUE THREAD

**Issue by gglusman** [SmartAPI/smartAPI#189]
## Transfer of Ownership

Fill this out if you would like to transfer ownership of an API entry to someone else or claim ownership of one.

**Note: This transfer of ownership requests can only come from a registered user and go to another registered user on SmartAPI**.

  

*Let's start! First, tell us who you are*

* **I'm am ...**

- [ ] the person transferring ownership of my API

- [x] the person that this API is being transferred to

- [ ] a third party requesting a special transfer (please provide details)

  

* What is the ***name*** and ***id*** of the API you would like to transfer? *eg. MyAPI : 124094327094378*

  Multiomics Wellness KP: 02af7d098ab304e80d6f4806c3527027
  

* What is the ***name*** and ***username*** of the person that this API currently belongs to? *eg. Jane Doe @janedoe1

  Ryan Roper @rtroper
  

* What is the ***name*** and ***username*** of the person that this API is being transferred to? *eg. John Doe @johndoe1*

  G Glusman @gglusman
  

* What is the reason this transfer of ownership is being requested?

  Ryan left the team a while ago, and I maintain/develop this KP.
  

Thank you! We will review this request ASAP and will inform you of the status of the transfer.

**Comment by marcodarko** [comment]
Hi. @gglusman 

You should have control over this entry now in your dashboard! (PS refresh your browser if it doesn't appear for some reason, in some cases the call gets cached but already checked and it belongs to you now.)  Thank you!
