### ISSUE TITLE
website typo and broken link

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#191]
user from Translator (thanks @gglusman!) noticed the typo in this screenshot "spedcification"

![image](https://github.com/SmartAPI/smartAPI/assets/2635409/698f6f12-db12-421e-825c-c19cc1310594)

and also that the "current specification" link on https://smart-api.info/documentation/openapi-specification returns a "page doesn't exist" error

**Comment by marcodarko** [comment]
Note to self: change links on doc file to absolute paths so web app doesn't try to render links to repo files

**Comment by micheldumontier** [comment]
@marcodarko sure, but I don't maintain this anymore. @newgene should comment more.

**Comment by newgene** [comment]
yes, already merged. leave it to you to close it after you verified everything works as expected @marcodarko.
