### ISSUE TITLE
clarify relationship between "owner", "created by" and "registered by"

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#198]
In https://smart-api.info/faq#transfer, we state:

> A transfer of ownership requests can be initiated by filling out a form. You will need the current owner information, recipient information, reason and any other relevant information to this transfer.

and the [issue template](https://github.com/SmartAPI/smartAPI/blob/master/.github/ISSUE_TEMPLATE/transfer.md) uses similar language around "owner".

However, the SmartAPI registrations themselves have one field for "Created By" and one for "Registered by".  We should clarify the relationship between these three terms and what permissions each allows.

**Comment by marcodarko** [comment]
I have made changes to the wording in all related pages and issue template so the "owner" is uniformly known as "Responsible Developer" and added a little more description as to where to find this information on the FAQ.

**Comment by marcodarko** [comment]
Clarified and used consistent language used and pointed to examples on FAQ
