### ISSUE TITLE
Metadata yaml file not updating properly when refreshing from git.

### ISSUE THREAD

**Issue by achave11** [SmartAPI/smartAPI#20]
I've made a couple of tag updates to my yaml file and pushed to github. They show on the raw file view, but when I go to the smart-api metadata file for api it doesn't seem to be containing all the changes. Here is the file for the 
#### Smart-api: 
[smart-api.yaml](http://smart-api.info/api/metadata/9c7027eec7ba101587f74e4b2ca2f7d2?format=yaml)

#### Raw github: 
[raw-github.yaml](https://raw.githubusercontent.com/achave11/workflow-execution-service-schemas/wes_smartapi/openapi/workflow_execution_service.openapi.yaml)

**Comment by marcodarko** [comment]
@achave11 Hi Abraham, 
Our latest release gives you the ability to refresh your api metadata via our new user dashboard. You can refresh each api individually.  We also refresh our apis daily now automatically too! Thanks for the great feedback and hope you enjoy our app!
