### ISSUE TITLE
Transfer of ownership of the SmartAPI registration for BigGIM-DrugResponse API

### ISSUE THREAD

**Issue by gloriachin** [SmartAPI/smartAPI#200]
### Transfer of ownership of the SmartAPI registration for BigGIM-DrugResponse API

* **I'm am Guangrong the person that this API is being transferred to.**

*  ***name*** and ***id*** of the API you would like to transfer:
Multiomics BigGIM-DrugResponse KP API  : adf20dd6ff23dfe18e8e012bde686e31

* What is the ***name*** and ***username*** of the person that this API currently belongs to? *
name: Chunlei Wu
username: newgene
  

* What is the ***name*** and ***username*** of the person that this API is being transferred to? *
name: Guangrong Qin
username: gloriachin

* What is the reason this transfer of ownership is being requested?
Requested by the BTE team.
  
 
@newgene @colleenXu

**Comment by marcodarko** [comment]
http://smart-api.info/registry?q=adf20dd6ff23dfe18e8e012bde686e31 item has been transferred to @gloriachin
