### ISSUE TITLE
invalid metakg graphml output for some queries

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#201]
For this newly released metakg `graphml` output feature, it works nicely in most of cases, however, I noticed this particular query outputs invalid `graphml` file:

https://smart-api.info/api/metakg/consolidated?q=api.name:BTE&size=3000&format=graphml

(The error is about `GeneticInheritance` node referenced in the edges but not defined in nodes)

This query works fine when set size to `2000`, where `GeneticInheritance` is not part of the output:

https://smart-api.info/api/metakg/consolidated?q=api.name:BTE&size=2000&format=graphml

**Comment by NikkiBytes** [comment]
This issue has been merged and is fixed.
