### ISSUE TITLE
enable API registration in the smartAPI API interface

### ISSUE THREAD

**Issue by micheldumontier** [SmartAPI/smartAPI#21]
Would be good for the smartAPI API to have a method for an authenticated user to post the url to the smartAPI description and register an API.  authorized users should be able to update/delete?

**Comment by newgene** [comment]
Hi @micheldumontier, what's the use case for this? It seems only making sense if users want to do a batch registration. 

Users can already update/delete his/her own APIs from the web interface.

I also think @cyrus0824 is working on two ways of auto-updating registered API metadata: 1) daily update of all API metadata; 2) a github commit hook which can trigger a refresh after a new commit.

**Comment by micheldumontier** [comment]
yes, i (and others) would like to have programmatic access to register an API, and not use the user interface. the smartAPI API should expose all methods.

**Comment by namespacestd0** [comment]
You can use the "Authentication" header to access the APIs by providing:
https://github.com/SmartAPI/smartAPI/blob/8b5dd9012ec4548022ff153e590f7f023bde5db3/src/handlers.py#L50
and access https://github.com/SmartAPI/smartAPI/blob/8b5dd9012ec4548022ff153e590f7f023bde5db3/src/handlers.py#L263
