### ISSUE TITLE
Add metakg field flag to SmartAPI records

### ISSUE THREAD

**Issue by marcodarko** [SmartAPI/smartAPI#218]
We need to add a new field (name not decided yet) under `_meta` to indicate whether this API's specification was included into the metaKG API.  We can follow the same criteria that this API's endpoint (api/metakg) used to determine whether this record should be truthy or false.  This new field should be checked during our daily backups/updates and update as necessary. 

```
{
  "included_in_metakg": true,
  "date_created": "2021-10-24T07:55:13.768377+00:00",
  "last_updated": "2023-10-27T07:01:25.247079+00:00",
  "url": "https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/semmeddb/smartapi.yaml",
  "username": "colleenXu"
}
```

**Comment by newgene** [comment]
I would suggest we call the new metadata field `has_metakg`, because not just the whole set of kg edges called `metakg`, each API has its own `metakg`, for those edges coming from this API.
