### ISSUE TITLE
Create json schema for x-bte extensions

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#236]
Similar to other OpenAPI extension schemas we support here:

https://github.com/SmartAPI/smartAPI/blob/77cdc450009beb52ee728071953203780b33a541/src/schemas.ini

Let's create json schema file for our `x-bte` extension too.

**Comment by newgene** [comment]
@NikkiBytes, @colleenXu had extensive experience of creating our `x-bte` extension metadata in SmartAPI registry, you both can work together on this issue.

**Comment by colleenXu** [comment]
Noting a previous issue https://github.com/biothings/biothings_explorer/issues/522.

**Comment by newgene** [comment]
@colleenXu thanks for reminding me the related issue. Let's consider this smartapi issue a sub-task of the the overall x-bte documention https://github.com/biothings/biothings_explorer/issues/522 issue.

I would like to push forward this issue and included @NikkiBytes to work with you.

**Comment by NikkiBytes** [comment]
New schema and example [here](https://github.com/NCATSTranslator/translator_extensions/tree/main/x-bte)
Closing as complete.
