### ISSUE TITLE
update smartapi's API metadata to include new metakg related endpoints

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#237]
Our SmartAPI's own API is registered here:

https://smart-api.info/registry?q=27a5b60716c3a401f2c021a5b718c5b1

Its metadata is here:

https://github.com/SmartAPI/smartapi_registry/blob/master/SmartAPI/smartapi_openapi.yml

Its live API documentation page renders here:

https://smart-api.info/ui/27a5b60716c3a401f2c021a5b718c5b1

**Comment by NikkiBytes** [comment]
Finished and merged PR here on SmartAPI: https://github.com/SmartAPI/smartapi_registry/pull/12
