### ISSUE TITLE
alignment of the badges on live API page

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#238]
A minor UI issue I noticed. It probably only shows on a large screen:

![image](https://github.com/SmartAPI/smartAPI/assets/130158/1f03da5c-c682-45cc-b1b2-8ddad0267c03)

but we should align those badges with the title.

**Comment by NikkiBytes** [comment]
Alignment is fixed. Noticed now the badge version number is being repeated:  
<img width="943" alt="Screen Shot 2024-09-25 at 1 50 47 PM" src="https://github.com/user-attachments/assets/e4c48503-e8d6-4ee8-9bb4-1200e12160c8">

**Comment by marcodarko** [comment]
Badges have moved to a lower section, rendering next the existing ones caused rendering issues and alignment issues that cannot be matched.
