### ISSUE TITLE
The first time visiting the site, it takes a long time to load when clicking on Registry

### ISSUE THREAD

**Issue by AviMaayan** [SmartAPI/smartAPI#24]

**Comment by cyrus0824** [comment]
Hi @AviMaayan, we enabled gzip compression on the smart-api server.  Additionally we tried to minimize the data requested from the server that populates the registry page.  From our tests, the registry page load time has decreased significantly.

In the future, if this continues to remain an issue, we may decide to implement client-side pagination, but for now I'm going to close this issue out - feel free to reopen if you continue to experience load time issues.
