### ISSUE TITLE
Support OpenAPI v3.1.0 schema validation

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#245]
We start to see registered API metadata using `v3.1.0` OpenAPI specification now:

http://smart-api.info/registry?q=beb82e00728d3824591caec8da3e63fc

It currently fails the validation against the `v3.0.0` schema defined in `src/schema.ini` file.

Let's add the support for `v3.1.0`

The JSON schema files used for validation from Swagger Editor are now available at:

https://github.com/swagger-api/apidom/tree/8a92ad810d94a0212c0d61a9159397ea9e34a161/packages/apidom-ls/src/services/validation/json-schema

or

https://github.com/swagger-api/validator-badge/tree/b9fd2182ea2ca6da1059c4c001f7514dc317ab22/src/main/resources/schemas

We will evaluate and pick a proper schema file to be used in SmartAPI.

Note that now OpenAPI `v3.0.x` and `v3.1.x` has different schema files, so we will need to create a new section for `openapi_v3.1` in `src/schema.ini` file, and adjust the dispatch logic in:

https://github.com/SmartAPI/smartAPI/blob/c27df4d5816ca7e6c620cdcd825373f7cc1c3b6a/src/controller/base.py

**Comment by marcodarko** [comment]
validation and support for version v3.1.0 is now supported in the API
