### ISSUE TITLE
issue templates seem not working any more

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#247]
Two issue templates we previously defined, under [.github/ISSUE_TEMPLATE](https://github.com/SmartAPI/smartAPI/tree/main/.github/ISSUE_TEMPLATE),  do not work any more. It's probably Github changed how it sets up the issue templates.

We might want to follow [the documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) to set them up again.

**Comment by marcodarko** [comment]
Issues were updated using the new options provided in Settings>Issues
