### ISSUE TITLE
SSL error when accessing SmartAPI API from requests or httpx

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#256]
```
In [27]: requests.get("https://smart-api.info/api/metakg")
```

with this SSL error:

```
SSLError: HTTPSConnectionPool(host='smart-api.info', port=443): Max retries exceeded with url: /api/metakg (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)')))
```

Same issue with `httpx` package.

Web browser works just fine. Must be SSL version issue, and web browser might be more tolerant.

**Comment by everaldorodrigo** [comment]
The [smartapi](https://smart-api.info/) is using HTTPS/TLS 1.3. It's the last version of the TLS.

In this case, the client needs to implement the TLS 1.3 to access it. Otherwise we get an error.

Another option is configuring the servers to accept older versions of TLS.

**Comment by newgene** [comment]
@everaldorodrigo is this addressed?

**Comment by everaldorodrigo** [comment]
@newgene yes it was addressed. Now the application is using TLS 1.2 and 1.3.
