### ISSUE TITLE
old TRAPI 1.4 OpenPredict and Knowledge Collaboratory registrations

### ISSUE THREAD

**Issue by CaseyTa** [SmartAPI/smartAPI#257]
Could you please either delete these old registrations or transfer them to me to delete? Thanks!

## Transfer of Ownership

Fill this out if you would like to transfer ownership of an API entry to someone else or claim ownership of one.

**Note: This transfer of ownership requests can only come from a registered user and go to another registered user on SmartAPI**.

  

*Let's start! First, tell us who you are*

* **I'm am ...**

- [ ] the person transferring ownership of my API

- [x] the person that this API is being transferred to

- [ ] a third party requesting a special transfer (please provide details)

  

* What is the ***name*** and ***id*** of the API you would like to transfer? *eg. MyAPI : 124094327094378*

OpenPredict: e9f69b81e755e163fdf6c41a2b5e07c0
Knowledge Collaboratory: 89054eff6ee6d91641d278d9ffdb3993
  

* What is the ***name*** and ***username*** of the person that this API currently belongs to? *eg. Jane Doe @janedoe1

  Vincent Emonet @vemonet
  

* What is the ***name*** and ***username*** of the person that this API is being transferred to? *eg. John Doe @johndoe1*

  Casey Ta @caseyta
  

* What is the reason this transfer of ownership is being requested?

  Vincent took a position elsewhere 
  

Thank you! We will review this request ASAP and will inform you of the status of the transfer.

**Comment by marcodarko** [comment]
Hi @CaseyTa 
I just deleted them! Let me know if there's anything else.  TY!

**Comment by CaseyTa** [comment]
@marcodarko Thank you!
