### ISSUE TITLE
requesting ownership transfer for ClinicalTrials KP and EHR Risk KP

### ISSUE THREAD

**Issue by gglusman** [SmartAPI/smartAPI#259]
## Transfer of Ownership

Fill this out if you would like to transfer ownership of an API entry to someone else or claim ownership of one.

**Note: This transfer of ownership requests can only come from a registered user and go to another registered user on SmartAPI**.

  

*Let's start! First, tell us who you are*

* **I'm am ...**

- [ ] the person transferring ownership of my API

- [x] the person that this API is being transferred to

- [ ] a third party requesting a special transfer (please provide details)

  

* What is the ***name*** and ***id*** of the API you would like to transfer? *eg. MyAPI : 124094327094378*

  Multiomics ClinicalTrials KP 08a5ddcde71b4bf838327ef469076acd
  Multiomics EHR Risk KP d86a24f6027ffe778f84ba10a7a1861a
  

* What is the ***name*** and ***username*** of the person that this API currently belongs to? *eg. Jane Doe @janedoe1

  Kamileh Narsinh @githubbit
  

* What is the ***name*** and ***username*** of the person that this API is being transferred to? *eg. John Doe @johndoe1*

  Gwênlyn Glusman @gglusman
  

* What is the reason this transfer of ownership is being requested?

  Kamileh left the project.
  

Thank you! We will review this request ASAP and will inform you of the status of the transfer.

**Comment by marcodarko** [comment]
Hi @gglusman they are now registered to you, refresh your dashboard and they should appear there now.  If there's anything else or if there's any issues please let me know.  Thank you!
