### ISSUE TITLE
Transfer ownership of Text Mined Cooccurrence API

### ISSUE THREAD

**Issue by bill-baumgartner** [SmartAPI/smartAPI#278]
Please transfer ownership of the [Text Mined Cooccurrence API](http://smart-api.info/registry?q=71fa2e0f0f1fe1ec67f4ddb719db5ef3) from `edgargaticaCU` to `bill-baumgartner`. Edgar is no longer part of our group. Thank you.

**Comment by marcodarko** [comment]
@bill-baumgartner Thanks for your patience, we had another issue preventing the transfer but it's been taken care of, and the API is under your control now. TY!
