### ISSUE TITLE
Add a permanent URL button for current search result

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#28]
"/registry" page currently already supports "q" and "tag" parameters, but when users search from the search box, there is no way to get a matching URL (e.g. share the search result to someone).

Two ways of doing this:

1. Using [HTML5 history](https://html5demos.com/history/) to make sure the current browser URL always matches the current search.

2. Add a permanent URL button/icon on the registry page for users to copy the URL

**Comment by marcodarko** [comment]
URL now updates dynamically to match the filters and queries the user makes on the registry page.  Owners filters are now supported as well. After any search a button to copy and share your search will appear.  Upon pasting that link all filters and queries will auto-populate for the user who you shared your view with.
