### ISSUE TITLE
Some API parameters not documented in Swagger/OpenAPI

### ISSUE THREAD

**Issue by u8sand** [SmartAPI/smartAPI#31]
I'm using a Swagger Client to access SmartAPI, but some parameters (currently, pagination-related parameters) are not documented in the spec making those arguments inaccessible. I therefore have no simple way to view more than the first 10 results of any query.

https://github.com/SmartAPI/smartAPI/blob/689f60681b86091631a3f799cdaa2f58d72246af/src/api/handlers.py#L75-L76

**Comment by newgene** [comment]
updated.

**Comment by u8sand** [comment]
Perfect, thank you
