### ISSUE TITLE
Broken link on https://smart-api.info for editor.

### ISSUE THREAD

**Issue by julie-sullivan** [SmartAPI/smartAPI#36]
https://smart-api.info/

If I scroll and click on the editor button in the middle of the page, I get this link:

```
http://smart-api.info/editor-oa3////////////////////
```

When I click on the `editor` link on the top right, I get the correct URL 

```
http://smart-api.info/editor/
```

Thanks!

**Comment by marcodarko** [comment]
We have updated that link to point to the right editor. New link points to the editor hosted in smartAPI. Thank you for bringing this up to our attention!
