### ISSUE TITLE
Registry Page Button State Preserves Across Pages

### ISSUE THREAD

**Issue by namespacestd0** [SmartAPI/smartAPI#37]
To reproduce the problem:
1. Open https://smart-api.info/registry
2. Click "SHOW DETAILS"
3. Go to the end of the page and click on the second page
4. Scroll back to the beginning of the current page
5. Now the button corresponds to the first item reads "HIDE DETAILS", but performs like "SHOW DETAILS".

Proposed Solution:
Maybe consider resetting the button state on page switch.

Limitation of this article:
Button states across other user interactions like search or filter are not tested. No information about the scale of operations to be able to observe this behavior. Need further examination.

Added here as suggested by @newgene

**Comment by marcodarko** [comment]
Used $set to add a new prop (showDetails) to each item prior to rendering to fix the issue of each registry item preserving it's values and view state.
