### ISSUE TITLE
Create a FAQ page 

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#39]
A FAQ page for some common questions we answer our users.

* How to delete an API

* Is my API metadata automatically updated if I modify the source metadata?

* How often API metadata is updated automatically?

* How to manually refresh my API metadata if I just made a change?

Each of questions should have an anchor to allow deep-linking.

**Comment by newgene** [comment]
* What's dashboard? And how to access it?

**Comment by newgene** [comment]
* Someone registered my API, can I claim the ownership of that API entry?

**Comment by marcodarko** [comment]
FAQ page has been added and can be viewed here: https://smart-api.info/faq

**Comment by newgene** [comment]
* Edited Metadata on github, but the raw github URL does not reflect the changes. What's going on?

**Comment by newgene** [comment]
Add this link to "Claim an API" issue: https://github.com/SmartAPI/smartAPI/issues/40

**Comment by marcodarko** [comment]
https://smart-api.info/faq has been added and updated
