### ISSUE TITLE
responsibleDeveloper and responsibleOrganization cause validation failure

### ISSUE THREAD

**Issue by stuppie** [SmartAPI/smartAPI#4]
The "responsibleDeveloper" and "responsibleOrganization" tags cause the swagger file to fail validation using external tools. There is an official way to extend the swagger schema using "patterned objects", where the field name MUST begin with x-. See [specifications](http://swagger.io/specification/). It would be nice to convert these to x-responsibleDeveloper and x-responsibleOrganization, respectively.

**Comment by micheldumontier** [comment]
Yes, in previous conversations, we have indeed determined that we will move to using the developer extensions. However, we are doing this at the same time as a move to openAPI v3.

**Comment by stuppie** [comment]
For others' info, the way I'm adding extra fields in garbanzo: https://github.com/stuppie/garbanzo/blob/2336ac5ec8635a326a34569a3bd525e9b7f41fc4/app.py#L33

**Comment by newgene** [comment]
closing this issue now, as it's not relevant anymore after we moved to the new smartapi specs based on v3 OpenAPI and using its "x-" based extensions.
