### ISSUE TITLE
claim an API

### ISSUE THREAD

**Issue by micheldumontier** [SmartAPI/smartAPI#40]
It's the case that I and others have registered APIs that we do not actively maintain. I would like for it to be possible for the maintainers of the API to claim an existing API, and for there to be a process in which the "ownership" of the smartAPI entry can be transferred to another account. The request should only come from a registered user, and should be accompanied with a message detailing the rationale for the transfer. Some evidence should be presented that supports their claim about ownership (name listed on official website or in API documentation), along with other information to follow up (e.g. full name, email address, phone number, github account).  Once the reviewed, the current API owner could then transfer the ownership to the other user.

**Comment by namespacestd0** [comment]
Thank you for the suggestion. 

We created an FAQ page in which we detailed the procedure based on your input and what we thought made sense: https://smart-api.info/faq#transfer

Here's a quote:

How can I transfer/claim the ownership of an API entry?
> Transfer of ownership requests can only come from a registered user, and should be accompanied with a message detailing the rationale for the transfer. Some evidence should be presented that supports your/their claim about ownership (name listed on official website or in API documentation), along with other information to follow up (e.g. full name, email address, phone number, github account). Once reviewed, the current API owner can then transfer the ownership to the other user. If you would like to transfer ownership to someone else or claim ownership of an API please contact us.

Please contact us if you have further comments.
