### ISSUE TITLE
add "how to cite" on smart-api.info site

### ISSUE THREAD

**Issue by micheldumontier** [SmartAPI/smartAPI#42]
it's important that users know how to cite the smartAPI work. We should indicate the primary citation and other papers that have resulted from this work. 

The primary citation is:

Zaveri, A., Dastgheib, S., Whetzel, T., Verborgh, R., Avillach, P., Korodi, G., Terryn, R., Jagodnik, K., Assis, P., Wu, C., Dumontier, M.: smartAPI: Towards a More Intelligent Network of Web APIs. In: Blomqvist, E., Maynard, D., Gangemi, A., Hoekstra, R., Hitzler, P., and Hartig, O. (eds.) Proceedings of the 14th ESWC. pp. 154–169. Springer (2017). https://doi.org/10.1007/978-3-319-58451-5_11

Secondary citations include

Shima Dastgheib, Trish Whetzel, Amrapali Zaveri, Cyrus Afrasiabi, Pedro Assis, Paul Avillach, Kathleen M. Jagodnik, Gabor Korodi, Marcin Pilarczyk, Jeff de Pons, Stephan C. Schürer, Raymond Terryn, Ruben Verborgh, Chunlei Wu, Michel Dumontier:
The SmartAPI Ecosystem for Making Web APIs FAIR. International Semantic Web Conference (Posters, Demos & Industry Tracks) 2017

**Comment by micheldumontier** [comment]
@marcodarko does it make sense to add this to the FAQ?

**Comment by marcodarko** [comment]
@micheldumontier yes, I think so. I'll work on it :) I'll ask Chunlei for help in the language if I need it.

**Comment by marcodarko** [comment]
Added some citation information and it's live now at https://smart-api.info/faq#citation
