### ISSUE TITLE
A couple APIs (from FAIR Metrics) missing server information, but still appear in SmartAPI registry

### ISSUE THREAD

**Issue by kevinxin90** [SmartAPI/smartAPI#43]
servers.url is a **required** field based on OpenAPI 3.0. But seems a couple of APIs in SmartAPI registry actually missed these fields, e.g. FAIR Metrics - Identifier Persistence. (These APIs from FAIR Metrics are based on swagger 2.0)

**Comment by namespacestd0** [comment]
Retroactive validation is not possible considering we have constantly changing schemas and thus the saved version represents our best effort to preserve a working version. Will consider adding a schema validation field to existing documents.

**Comment by newgene** [comment]
swagger specs have `host` and `basePath` fields to indicate the same info from `servers.url` (OpenAPI v3), both fields are not required.  See the swagger JSON schema we use for the validation.

There is no validation error for these swagger API entries. While it's not a good practice to miss `host` and `basePath` fields, I don't think we need to fix anything here.
