### ISSUE TITLE
Minor UI tweak: registry page seems refreshing twice

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#45]
When go to a registry page:

https://smart-api.info/registry

or 

https://smart-api.info/registry?q=fa32b87fdaec64ef11432f695c71b989

The content in the main panel seems refreshing twice. It happens only at the first load of the page at a new tab. It won't happen again when I hit the "reload" button.

Minor UI issue, not something critical.

**Comment by marcodarko** [comment]
Registry code has been updated to prevent this behaviour
