### ISSUE TITLE
handle PyYAML yaml.load(input) Deprecation

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#46]
`transform.get_api_metadata_by_url(url)` now create a deprecation msg when the input is a yaml file, need to handle it properly as documented here:

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Shall we use `SafeLoader` or `FullLoader`?

**Comment by namespacestd0** [comment]
It should be okay to use the `SafeLoader`. The `FullLoader` supports additional python class object serialization (like pickle) which does not seem to be necessary.

[Reference] https://pyyaml.org/wiki/PyYAMLDocumentation#yaml-tags-and-python-types

**Comment by namespacestd0** [comment]
Resovled in https://github.com/SmartAPI/smartAPI/commit/8d9f8088196fdb7cb683d5c0cf676476ea36a039

**Comment by namespacestd0** [comment]
Deployed on the production server.
