### ISSUE TITLE
Annotate UniProtKB humsavar from MyVariant.info (variant-to-disease)

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#49]

**Comment by kevinxin90** [comment]
Done

[SmartAPI Query Interface](http://smart-api.info/ui/09c8782d9f4027712e65b95424adba79)
[SmartAPI Annotation File](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/myvariant.info/openapi_full.yml)
