### ISSUE TITLE
Annotate OpenTargets API (disease-to-drugtargets)

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#50]

**Comment by kevinxin90** [comment]
Done:

[SmartAPI Query Interface](http://smart-api.info/ui/542ba165e1b4227854cf7c0a8addcc79)
[SmartAPI Annotation File](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/opentarget/smartapi.yaml)
