### ISSUE TITLE
Annotate RGD API (gene-to-phenotype/disease)

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#51]

**Comment by kevinxin90** [comment]
Done:

[SmartAPI Query Interface](http://smart-api.info/ui/eb28713e2e23160e80e88f3a5dabcca4)
[SmartAPI Annotation File](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/RGD/smartapi.yaml)
