### ISSUE TITLE
Support API parameter accepts a list as the input

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#56]

**Comment by kevinxin90** [comment]
This feature is implemented.

See an example annotation file [here](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/mygene.info/openapi_full.yml)

There is a SmartAPI field "x-bte-kgs-operations" added under components. And in that field, when "supportBatch" is specified to be True, the API could take a list as input. And "inputSeperator" specifies how the list of input is seperated.
