### ISSUE TITLE
api-interoperability@googlegroups.com email bounces

### ISSUE THREAD

**Issue by cborromeo** [SmartAPI/smartAPI#62]
Hello,
  I tried emailing the api-interoperability@googlegroups.com address on the FAQ but it just bounces.  I need some help deleting an existing API from my organization, but I cannot find the account information used to create it.
Thanks,
Chuck

**Comment by newgene** [comment]
@cborromeo I just checked this google group still works:

https://groups.google.com/forum/#!forum/api-interoperability

could be you are not signed up there and the group moderator did not approve your incoming email within a time frame.

Regardless, you can let us know your API title registered at SmartAPI, we will help you recover the information you need.

Once you log in using your github account, you can delete an API you registered from the "dashboard": https://smart-api.info/faq#delete

**Comment by micheldumontier** [comment]
ok, requests have been approved. however this list is not in sync with the list that was being maintained by NIH staff.
