### ISSUE TITLE
Update to use OAS 3.0.3 recently released

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#65]
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.3

We should check the places on our side need to be updated.

**Comment by newgene** [comment]
need to update the json-schema URL here if there is updates:

https://github.com/SmartAPI/smartAPI/blob/master/src/web/api/transform.py#L23

**Comment by namespacestd0** [comment]
Update endpoint is https://github.com/SmartAPI/smartAPI/blob/master/src/schemas.ini now.

**Comment by NikkiBytes** [comment]
@newgene I think we updated this recently?

**Comment by NikkiBytes** [comment]
Issue updated in file.
