### ISSUE TITLE
Setup status check for new KP API from Segment 1

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#66]
After registered them in SmartAPI registry, example values should be added to enable the status check for these APIs:

https://github.com/biothings/pending.api/issues/5
https://github.com/biothings/pending.api/issues/6
https://github.com/biothings/pending.api/issues/7

**Comment by kevinxin90** [comment]
Examples for these APIs are added. Waiting for SmartAPI backend to refresh and display the badge.

**Comment by kevinxin90** [comment]
All newly added APIs have passed tests.

EBIgene2phenotype
<img width="741" alt="Screen Shot 2020-03-13 at 4 26 42 PM" src="https://user-images.githubusercontent.com/10997542/76669131-8d8af900-6547-11ea-9ff5-cd86557fb4cb.png">

MGIgene2phenotype
<img width="736" alt="Screen Shot 2020-03-13 at 4 26 55 PM" src="https://user-images.githubusercontent.com/10997542/76669147-9ed40580-6547-11ea-8ec3-b8adcd57d945.png">

DISEASES
<img width="739" alt="Screen Shot 2020-03-13 at 4 27 08 PM" src="https://user-images.githubusercontent.com/10997542/76669155-a5fb1380-6547-11ea-84cf-57c9b0110d11.png">
