### ISSUE TITLE
add an "Edit" button next to the original metadata URL

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#71]
If the metadata URL is from a known repo (e.g. github), we can add an "Edit" button next to it, pointing to the repo's own edit interface. A handy feature to add.

**Comment by polyg314** [comment]
Pull request submitted at https://github.com/SmartAPI/smartAPI/pull/78

**Comment by polyg314** [comment]
Pull request for this now at https://github.com/SmartAPI/smartAPI/pull/79
(only showing relevant changes now - not the slack integration changes as well)
