### ISSUE TITLE
create a "translator" specific portal page

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#72]
This portal page serves as the landing page for Translator API (e.g. /portal/translator):

* General API best-practices
* Create OpenAPI metadata
* Annotate API with SmartAPI extensions
* Reasoner API section (pending)

Other contents:
* entry to the translator registry (/registry/translator)
* meta-KG graph and summary

**Comment by newgene** [comment]
Some previous docs are available here: 

https://github.com/NCATS-Tangerine/translator-api-registry

**Comment by marcodarko** [comment]
BUILD TRANSLATOR KP API

1 Create Your API 
-generate from md file (HTTPS, gzip,CORS, etc)
-bt sdk includes all of this

2 Document your API with metadata
a.
providing openAPI metadata
-ex OpenAPI v3 metadata from md file
- v2 to v3 example
b.
providing semantics for API I/O
https://x-bte-extension.readthedocs.io/en/latest/x-bte-kgs-operation.html

NAVIGATE TRANSLATOR KP API

1 API registry
2 what's meta-kg
- embed meta-kg
-json dump meta-kg

**Comment by marcodarko** [comment]
closing as https://smart-api.info/portal/translator is now live, any additional updates please reopen or create a new issue.
