### ISSUE TITLE
Consistency of the output from different SmartAPI API Endpoints

### ISSUE THREAD

**Issue by kevinxin90** [SmartAPI/smartAPI#74]
Example:

**/metadata/{api_id} endpoint**: https://smart-api.info/api/metadata/8f08d1446e0bb9c2b323713ce83e2bd3

The above query returns SmartAPI Specification for MyChem.info.

**/query endpoint**: https://smart-api.info/api/query?q=mychem.info

The above query also returns SmartAPI Specification for MyChem.info. 

Compare both queries above. The structure of returned results are different for the **paths** field. We need to make it consistent.

**Comment by namespacestd0** [comment]
Now enforced in https://github.com/SmartAPI/smartAPI/blob/8b5dd9012ec4548022ff153e590f7f023bde5db3/src/pipeline.py#L122
