### ISSUE TITLE
setup slack notification for new API registration

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#75]
The notification can be tag specific, e.g. API registered with "translator" tag can send a notification to a specific slack channel.

**Comment by newgene** [comment]
similar code from biothings/biothings.api repo for sending slack msg:

https://github.com/biothings/biothings.api/blob/master/biothings/utils/slack.py

**Comment by polyg314** [comment]
Pull request for updates at: https://github.com/SmartAPI/smartAPI/pull/77#pullrequestreview-447694079
