### ISSUE TITLE
customize meta tags for each registry record

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#76]
It looks like each registry entry has the same meta tags.  For example, the [ChEMBL record](https://smart-api.info/registry?q=71add13e7c8b26b0046cfb8cf5092395):

```
<meta property="og:title" content="SmartAPI | Building a connected network of FAIR APIs">
<meta name="description" content="The SmartAPI project aims to maximize the FAIRness (Findability, Accessibility, Interoperability, and Reusability) of web-based Application Programming Interfaces (APIs)">
<meta property="og:description" content="The SmartAPI project aims to maximize the FAIRness (Findability, Accessibility, Interoperability, and Reusability) of web-based Application Programming Interfaces (APIs)">
```

Seems like it would be better for SEO purposes if each page had more specific information about the resource being described?

**Comment by newgene** [comment]
👍 For example, this slack notification for new API registration shows the same preview content for different API, ideally, it should includes API's own title and part of description.

![image](https://user-images.githubusercontent.com/130158/86271016-0c508400-bb81-11ea-9c63-4131e34826cf.png)

**Comment by marcodarko** [comment]
https://smart-api.info/ui/bee3622cff00265a07cf3fd9828be2bf

I have updated the meta tags dynamically to match the details of each API loaded into Swagger UI
