### ISSUE TITLE
Garbanzo API isn't parsed correctly

### ISSUE THREAD

**Issue by stuppie** [SmartAPI/smartAPI#8]
See instructions in https://github.com/WebsmartAPI/smartAPI/issues/5
When you look at the page in the swagger editor ([link](http://smart-api.info/editor/#/?import=http://smart-api.info/api/metadata/R2FyYmFuem8gQVBJfDEuMC4xMTN8R3JlZyBTdHVwcA==)) its missing all of the parameters.

**Comment by twhetzel** [comment]
@stuppie how is the page in the link generated?

**Comment by stuppie** [comment]
The swagger.json file is being auto-generated with [flask_restplus](http://flask-restplus.readthedocs.io/en/stable/swagger.html). The source code is [here](https://github.com/stuppie/garbanzo/blob/master/app.py).

**Comment by twhetzel** [comment]
So is it flask_restplus or the smart-api editor that is generating the json without parameters?

**Comment by newgene** [comment]
@twhetzel I think it's the same JSON as in #5. Now saving it in editor has no 500 error, but after saving, when loading this API in the editor again (from the registry), the `parameters` are all missing. Need to double check your fix for #5. 

From this:

http://smart-api.info/api/metadata/R2FyYmFuem8gQVBJfDEuMC4xMTJ8R3JlZyBTdHVwcA==?raw=1
(this is the raw json object after conversion)

`"httpOperation": "parameters"` under "operations" does not look correct to me.

**Comment by stuppie** [comment]
@newgene Yes, correct, thanks

**Comment by newgene** [comment]
closing this issue now. It's not relevant anymore after we moved to the new smartAPI specs based on v3 OpenAPI and using its extension mechanism.
