### ISSUE TITLE
Refactor and Upgrade Biothings Version

### ISSUE THREAD

**Issue by namespacestd0** [SmartAPI/smartAPI#80]
### web.api.query_builder
example: https://github.com/biothings/discovery-app/blob/master/discovery/pipeline.py
### web.api.handlers
example: https://github.com/biothings/discovery-app/blob/master/discovery/web/api/dataset.py

### web.api.es 
example: https://github.com/biothings/discovery-app/blob/master/discovery/utils/controllers.py
### web.api.transform
example: https://github.com/biothings/discovery-app/blob/master/discovery/data/dataset.py

**Comment by marcodarko** [comment]
Currently done upgrading to ES-latest and dsl matching version. Will need to consult with Jerry to learn next steps dealing with BT.

**Comment by marcodarko** [comment]
Prod has been upgraded and has been running using latest biothings and ES/ES-dsl versions Jan 30~ c684860a398c96054858d1f64c74aa7736f416e2
