### ISSUE TITLE
invalid tags with spaces in "most active" list

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#81]
tags with spaces are not working properly in the list of "most active" tags:

![image](https://user-images.githubusercontent.com/2635409/92419113-51180e80-f120-11ea-9e1d-11a8ce3dddcd.png)

I actually think we should not allow tags with spaces...

**Comment by marcodarko** [comment]
I have fixed this, you should be able to activate that filter. Having said that I have to change the name to most popular "filters" since that includes owners and tags.
