### ISSUE TITLE
changing behavior of tags

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#82]
Suppose I get to a API-specific page e.g., https://smart-api.info/registry?q=5219cefb9d2b8d5df08c3a956fdd20f3 through one of the slack notifications, for example.  If I click on any of the links in the row of tags, I get unexpected behavior. 

![image](https://user-images.githubusercontent.com/2635409/92419248-28444900-f121-11ea-8b63-f1bd5355cace.png)

For example, if I click `#disease`, I was expecting to see other APIs that also have the disease tag, but I actually only see the one API because the tag is `ANDed` to the existing query with the API ID.  (e.g., https://smart-api.info/registry?q=5219cefb9d2b8d5df08c3a956fdd20f3&tags=gene)

The tag behavior is as expected in cases where the query returns more than one result e.g., https://smart-api.info/registry?q=tcga -> https://smart-api.info/registry?q=tcga&tags=gene

One solution *might* be to change the behavior of those hyperlinks depending on whether the search query returns one result or multiple results.  This would mirror the current design -- when only one result is returned, then the "Show Details" section is expanded.  Personally, I think a better design would be to have a formal "API details page" (e.g., https://smart-api.info/api/5219cefb9d2b8d5df08c3a956fdd20f3), and then the tag behavior can naturally be different depending on whether you're on "Search results" or "API details".  My guess is that this will also be better for SEO...

**Comment by marcodarko** [comment]
link tags behave as new searches for that tag only you should be able to click on those tags and search for APIs with that tag. Same logic applied for most popular tags section.

**Comment by marcodarko** [comment]
We currently do have an api page but we use: [https://smart-api.info/ui/5219cefb9d2b8d5df08c3a956fdd20f3](https://smart-api.info/ui/5219cefb9d2b8d5df08c3a956fdd20f3)
That page's metadata is customized to that particular API. The reason we expand when only one search result is just for convenience for the user not so simulate an API page but anyway just wanted to point out that we do have a dedicated page for each API, is that what you had in mind?
