### ISSUE TITLE
add a sitemap.xml?

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#84]
Right now, google search results are a mix of "registry" pages, "editor" pages, and "tag" searches.  For example
https://www.google.com/search?q=site%3Asmart-api.info+cord, 

![image](https://user-images.githubusercontent.com/2635409/92419964-870bc180-f125-11ea-82c8-fe722db235da.png)

Perhaps a sitemap.xml and/or a robots.txt would better route people who come via search engines (and overall improve SEO)?

**Comment by newgene** [comment]
should disallow /editor URLs too.

**Comment by marcodarko** [comment]
We have a sitemap now https://smart-api.info/sitemap.xml if anything needs to be added or removed we can adjust as needed.
