### ISSUE TITLE
"recently updated" sorting doesn't appear to be working

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#88]
When selecting the "Recently updated" sorting option at https://smart-api.info/registry, the first three records returned are currently:

**BioLink API**: Updated: September 11, 2020
**Charon**: Updated: October 27, 2019
**HuBMAP Entity APIs**: Updated: August 5, 2020

**Comment by marcodarko** [comment]
Issue seems to be fixed now with latest code, using Vuex to solve reactiveness issue that created issue.
