### ISSUE TITLE
Improve registry query ranking

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#89]
We should improve the ranking of the returned hits from the registry.

For example, when querying "text mining", the matched API entry on the title does not appear on the top.

Most likely this can be fixed by weighting on the different metadata fields.

**Comment by newgene** [comment]
as another example, search for "smartapi", the SmartAPI API entry is not on the top.

**Comment by marcodarko** [comment]
info.title has been boosted to 5.0 to improve results ranking based on title.
