### ISSUE TITLE
Open API in OpenAPI-GUI

### ISSUE THREAD

**Issue by MikeRalphson** [SmartAPI/smartAPI#9]
I noticed from GitHub traffic that you have a link to OpenAPI-GUI at http://dev.smart-api.info/openapi-gui/

I have just added functionality to import an OpenAPI / Swagger 2.0 definition from a `?url=` query parameter, possibly this will be useful for you. Please don't hesitate to ask if there's anything else which would make OpenAPI-GUI more useful for yourselves.

**Comment by micheldumontier** [comment]
great!  however, i have problem in a document like this one: http://dev.smart-api.info/openapi-gui/?url=https://raw.githubusercontent.com/bio-ontology-research-group/lodvectors/master/apidocs/smartapi3.yaml 

says "TypeError: Cannot read property 'contact' of undefined"
not sure what the probem is....
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#contactObject

**Comment by MikeRalphson** [comment]
Yes, the ability to load YAML definitions via url is in the most recent commit so your copy might need updating. You can see it working here: http://openapi-gui.herokuapp.com/?url=https://raw.githubusercontent.com/bio-ontology-research-group/lodvectors/master/apidocs/smartapi3.yaml

**Comment by micheldumontier** [comment]
@newgene can we update the opeapi-gui app on the server?

**Comment by newgene** [comment]
@MikeRalphson @micheldumontier awesome! Just updated.
