### ISSUE TITLE
slug with hyphen fails

### ISSUE THREAD

**Issue by CaseyTa** [SmartAPI/smartAPI#90]
It seems that trying to create a slug with a hyphen in it does not work properly. I tried creating `cohd-covid.smart-api.info`, and I received messages indicating that the slug was successfully created. However, visiting `cohd-covid.smart-api.info` did not lead to the API documentation. Editing the slug to `cohdcovid.smart-api.info` worked immediately. 

The interface for creating a slug warns users when adding invalid characters like `.`, but no warning was generated for the hyphen.

**Comment by marcodarko** [comment]
Hi Casey, thanks for letting us know about this bug we will take care of it soon!

**Comment by namespacestd0** [comment]
Update, "-" is explicitly supported in the backend, consider checking nginx setting and frontend compatibility.

**Comment by marcodarko** [comment]
Providing an update here.  Sorry for the delay first of all, this got caught in the middle of a major refactor/upgrade but soon this should be resolved once we approve our dev version and push to production.

**Comment by namespacestd0** [comment]
Assume any outstanding changes should be deployed now.
