### ISSUE TITLE
Make SmartAPI's own API a special "api" slug name

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#92]
We should make SmartAPI a special case with "api" as its slug name, so that https://api.smart-api.info will the same page of this URL:

https://smart-api.info/ui/27a5b60716c3a401f2c021a5b718c5b1

(normally, slug name should be 4-50 chars, shorter than 4-char names are reserved. And this "api" one is a good example as a reserved slug name)

**Comment by newgene** [comment]
Once it's live, we should add an "API" link to the header bar.

**Comment by namespacestd0** [comment]
To formalize this, the solution should be handler level keyword reservation and using controller level utility to create the slug.

**Comment by namespacestd0** [comment]
Related to https://github.com/SmartAPI/smartAPI/pull/112
