### ISSUE TITLE
"Filters Most Active" box on registry page should differentiate tag and owner filters

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#93]
See this screenshot, let's change the owner filter in the list with a leading `@` instead of `#`, that way two types of filters can display more intuitively (typically `#` indicates it's a tag):

![image](https://user-images.githubusercontent.com/130158/104378751-57a70000-54dd-11eb-9119-72d23909995c.png)

**Comment by marcodarko** [comment]
[
<img width="307" alt="Screen Shot 2021-01-21 at 8 28 22 AM" src="https://user-images.githubusercontent.com/23092057/105380374-a716bb80-5bc2-11eb-91a4-39832882d476.png">
](url) Updated to show different symbols for each type
