### ISSUE TITLE
Enum not working for UI

### ISSUE THREAD

**Issue by kevinxin90** [SmartAPI/smartAPI#94]
SmartAPI Example: https://smart-api.info/ui/dc91716f44207d2e1287c727f281d339

- SmartAPI spec:

<img width="522" alt="Screen Shot 2021-01-19 at 10 20 14 AM" src="https://user-images.githubusercontent.com/10997542/105076527-026c7080-5a40-11eb-8ced-9480e00df7f5.png">

- UI display in SmartAPI (wrong):

<img width="602" alt="Screen Shot 2021-01-19 at 10 20 20 AM" src="https://user-images.githubusercontent.com/10997542/105076537-07312480-5a40-11eb-810c-ebec6e7f150f.png">

- UI display from other OpenAPI editor (correct)

**Enum are working in other OpenAPI editors: https://editor.swagger.io/**

<img width="602" alt="Screen Shot 2021-01-19 at 10 24 28 AM" src="https://user-images.githubusercontent.com/10997542/105076890-89214d80-5a40-11eb-9b2f-d141351f1e76.png">

**Comment by marcodarko** [comment]
strange, our renders as a p tag and in the swagger ui site it renders as a select tag...

**Comment by marcodarko** [comment]
https://smart-api.info/ui/dc91716f44207d2e1287c727f281d339#/1.0.0/get_v1_team__team_name__predicates added css to fix that bug. Conflicting css was hiding it.
