### ISSUE TITLE
faq item for manual refresh needs an update

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#95]
https://smart-api.info/faq#refresh

![image](https://user-images.githubusercontent.com/130158/105114771-6e6cca00-5a7c-11eb-92f0-0f096a8e1c3c.png)

**Comment by marcodarko** [comment]
"If you want to update your metadata to its latest version quickly manual refreshes can be triggered from your user dashboard. Just click the green refresh button and our system will do the rest." Updated to be more relevant to the question

**Comment by newgene** [comment]
@marcodarko add a hyperlink to "user dashboard" in the text?

**Comment by marcodarko** [comment]
ah, yes! sorry I added now
