### ISSUE TITLE
Delete these outdated APIs

### ISSUE THREAD

**Issue by colleenXu** [SmartAPI/smartAPI#96]
These APIs were registered by devs who aren't in Translator anymore. The idea is to delete them and they'll be re-registered under a different developer if Translator still needs them. 

DATE API 26ce0569ba5b82902148069b4c3e51b4
NSIDES b2dd6372009df54206670648e16eaa90
∆QTDb API c43e12f0bdc350310288a2ec4db237c9

@marcodarko @namespacestd0

**Comment by marcodarko** [comment]
Puff! Deleted!
