### ISSUE TITLE
"no preview available" on slack's phone notification when SmartAPI sends a slack notification

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#97]
When SmartAPI sends a slack notification for certain APIs (e.g. a translator API) upon their registration, the slack mobile app shows a phone notification with "no preview available". Ideally, some preview content would be nice to show here.

This is how it looks like on my Android phone, comparing to another notification with some preview text:

![slack notification](https://user-images.githubusercontent.com/130158/106666105-0332f580-655c-11eb-9729-fb22f2ce9d63.png)

Looks like there is a solution described here:

https://github.com/alexkvak/teamcity-slack/blob/master/README.md#message-preview-

and in this issue: 

https://github.com/alexkvak/teamcity-slack/issues/36

**Comment by marcodarko** [comment]
Default plain text has been added, rich markdown is not supported on some mobile devices.

**Comment by rpriyanshu9** [comment]
@marcodarko could you point me to the location, where you added the plain text?

**Comment by marcodarko** [comment]
@rpriyanshu9 I believe it's in this util module:  https://github.com/SmartAPI/smartAPI/blob/master/src/utils/notification.py

**Comment by rpriyanshu9** [comment]
perfect, thanks @marcodarko 🙏🏼
